// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: CreateService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/create_mock_gen.go . CreateService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateService is a mock of CreateService interface.
type MockCreateService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateServiceMockRecorder
	isgomock struct{}
}

// MockCreateServiceMockRecorder is the mock recorder for MockCreateService.
type MockCreateServiceMockRecorder struct {
	mock *MockCreateService
}

// NewMockCreateService creates a new mock instance.
func NewMockCreateService(ctrl *gomock.Controller) *MockCreateService {
	mock := &MockCreateService{ctrl: ctrl}
	mock.recorder = &MockCreateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateService) EXPECT() *MockCreateServiceMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockCreateService) CreateItem(ctx context.Context, userID int, item *model.ItemDecrypted) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, userID, item)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockCreateServiceMockRecorder) CreateItem(ctx, userID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockCreateService)(nil).CreateItem), ctx, userID, item)
}
