// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: CreateFileService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/create_file_mock_gen.go . CreateFileService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateFileService is a mock of CreateFileService interface.
type MockCreateFileService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateFileServiceMockRecorder
	isgomock struct{}
}

// MockCreateFileServiceMockRecorder is the mock recorder for MockCreateFileService.
type MockCreateFileServiceMockRecorder struct {
	mock *MockCreateFileService
}

// NewMockCreateFileService creates a new mock instance.
func NewMockCreateFileService(ctrl *gomock.Controller) *MockCreateFileService {
	mock := &MockCreateFileService{ctrl: ctrl}
	mock.recorder = &MockCreateFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateFileService) EXPECT() *MockCreateFileServiceMockRecorder {
	return m.recorder
}

// CreateFileItem mocks base method.
func (m *MockCreateFileService) CreateFileItem(ctx context.Context, userID int, item *model.ItemDecrypted, fileContentReader multipart.File, contentType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileItem", ctx, userID, item, fileContentReader, contentType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileItem indicates an expected call of CreateFileItem.
func (mr *MockCreateFileServiceMockRecorder) CreateFileItem(ctx, userID, item, fileContentReader, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileItem", reflect.TypeOf((*MockCreateFileService)(nil).CreateFileItem), ctx, userID, item, fileContentReader, contentType)
}
