// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: DeleteService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/delete_mock_gen.go . DeleteService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteService is a mock of DeleteService interface.
type MockDeleteService struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteServiceMockRecorder
	isgomock struct{}
}

// MockDeleteServiceMockRecorder is the mock recorder for MockDeleteService.
type MockDeleteServiceMockRecorder struct {
	mock *MockDeleteService
}

// NewMockDeleteService creates a new mock instance.
func NewMockDeleteService(ctrl *gomock.Controller) *MockDeleteService {
	mock := &MockDeleteService{ctrl: ctrl}
	mock.recorder = &MockDeleteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteService) EXPECT() *MockDeleteServiceMockRecorder {
	return m.recorder
}

// DeleteItem mocks base method.
func (m *MockDeleteService) DeleteItem(ctx context.Context, userID int, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockDeleteServiceMockRecorder) DeleteItem(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockDeleteService)(nil).DeleteItem), ctx, userID, title)
}
