// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: GetService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/get_mock_gen.go . GetService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetService is a mock of GetService interface.
type MockGetService struct {
	ctrl     *gomock.Controller
	recorder *MockGetServiceMockRecorder
	isgomock struct{}
}

// MockGetServiceMockRecorder is the mock recorder for MockGetService.
type MockGetServiceMockRecorder struct {
	mock *MockGetService
}

// NewMockGetService creates a new mock instance.
func NewMockGetService(ctrl *gomock.Controller) *MockGetService {
	mock := &MockGetService{ctrl: ctrl}
	mock.recorder = &MockGetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetService) EXPECT() *MockGetServiceMockRecorder {
	return m.recorder
}

// GetItemByTitle mocks base method.
func (m *MockGetService) GetItemByTitle(ctx context.Context, userID int, title string) (*model.ItemDecrypted, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByTitle", ctx, userID, title)
	ret0, _ := ret[0].(*model.ItemDecrypted)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByTitle indicates an expected call of GetItemByTitle.
func (mr *MockGetServiceMockRecorder) GetItemByTitle(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByTitle", reflect.TypeOf((*MockGetService)(nil).GetItemByTitle), ctx, userID, title)
}
