// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: GetFileService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/get_file_mock_gen.go . GetFileService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	io "io"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockGetFileService is a mock of GetFileService interface.
type MockGetFileService struct {
	ctrl     *gomock.Controller
	recorder *MockGetFileServiceMockRecorder
	isgomock struct{}
}

// MockGetFileServiceMockRecorder is the mock recorder for MockGetFileService.
type MockGetFileServiceMockRecorder struct {
	mock *MockGetFileService
}

// NewMockGetFileService creates a new mock instance.
func NewMockGetFileService(ctrl *gomock.Controller) *MockGetFileService {
	mock := &MockGetFileService{ctrl: ctrl}
	mock.recorder = &MockGetFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetFileService) EXPECT() *MockGetFileServiceMockRecorder {
	return m.recorder
}

// GetFileByItem mocks base method.
func (m *MockGetFileService) GetFileByItem(ctx context.Context, userID int, item *model.ItemEncrypted) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByItem", ctx, userID, item)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByItem indicates an expected call of GetFileByItem.
func (mr *MockGetFileServiceMockRecorder) GetFileByItem(ctx, userID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByItem", reflect.TypeOf((*MockGetFileService)(nil).GetFileByItem), ctx, userID, item)
}

// GetItemByTitle mocks base method.
func (m *MockGetFileService) GetItemByTitle(ctx context.Context, userID int, title string) (*model.ItemEncrypted, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByTitle", ctx, userID, title)
	ret0, _ := ret[0].(*model.ItemEncrypted)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByTitle indicates an expected call of GetItemByTitle.
func (mr *MockGetFileServiceMockRecorder) GetItemByTitle(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByTitle", reflect.TypeOf((*MockGetFileService)(nil).GetItemByTitle), ctx, userID, title)
}
