// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: ItemsService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/items_mock_gen.go . ItemsService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockItemsService is a mock of ItemsService interface.
type MockItemsService struct {
	ctrl     *gomock.Controller
	recorder *MockItemsServiceMockRecorder
	isgomock struct{}
}

// MockItemsServiceMockRecorder is the mock recorder for MockItemsService.
type MockItemsServiceMockRecorder struct {
	mock *MockItemsService
}

// NewMockItemsService creates a new mock instance.
func NewMockItemsService(ctrl *gomock.Controller) *MockItemsService {
	mock := &MockItemsService{ctrl: ctrl}
	mock.recorder = &MockItemsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemsService) EXPECT() *MockItemsServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockItemsService) List(ctx context.Context, userID int, iType model.ItemType) ([]model.ItemMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, iType)
	ret0, _ := ret[0].([]model.ItemMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockItemsServiceMockRecorder) List(ctx, userID, iType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockItemsService)(nil).List), ctx, userID, iType)
}
