// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: UpdateService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/update_mock_gen.go . UpdateService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateService is a mock of UpdateService interface.
type MockUpdateService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceMockRecorder
	isgomock struct{}
}

// MockUpdateServiceMockRecorder is the mock recorder for MockUpdateService.
type MockUpdateServiceMockRecorder struct {
	mock *MockUpdateService
}

// NewMockUpdateService creates a new mock instance.
func NewMockUpdateService(ctrl *gomock.Controller) *MockUpdateService {
	mock := &MockUpdateService{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateService) EXPECT() *MockUpdateServiceMockRecorder {
	return m.recorder
}

// UpdateItem mocks base method.
func (m *MockUpdateService) UpdateItem(ctx context.Context, userID int, title string, item *model.ItemDecrypted) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, userID, title, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockUpdateServiceMockRecorder) UpdateItem(ctx, userID, title, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockUpdateService)(nil).UpdateItem), ctx, userID, title, item)
}
