// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/api/handlers (interfaces: UpdateFileService)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/update_file_mock_gen.go . UpdateFileService
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateFileService is a mock of UpdateFileService interface.
type MockUpdateFileService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateFileServiceMockRecorder
	isgomock struct{}
}

// MockUpdateFileServiceMockRecorder is the mock recorder for MockUpdateFileService.
type MockUpdateFileServiceMockRecorder struct {
	mock *MockUpdateFileService
}

// NewMockUpdateFileService creates a new mock instance.
func NewMockUpdateFileService(ctrl *gomock.Controller) *MockUpdateFileService {
	mock := &MockUpdateFileService{ctrl: ctrl}
	mock.recorder = &MockUpdateFileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateFileService) EXPECT() *MockUpdateFileServiceMockRecorder {
	return m.recorder
}

// UpdateFileItem mocks base method.
func (m *MockUpdateFileService) UpdateFileItem(ctx context.Context, userID int, oldTitle string, item *model.ItemDecrypted, fileContentReader multipart.File, contentType string, expectedRevision int64) (*model.ItemDecrypted, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileItem", ctx, userID, oldTitle, item, fileContentReader, contentType, expectedRevision)
	ret0, _ := ret[0].(*model.ItemDecrypted)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateFileItem indicates an expected call of UpdateFileItem.
func (mr *MockUpdateFileServiceMockRecorder) UpdateFileItem(ctx, userID, oldTitle, item, fileContentReader, contentType, expectedRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileItem", reflect.TypeOf((*MockUpdateFileService)(nil).UpdateFileItem), ctx, userID, oldTitle, item, fileContentReader, contentType, expectedRevision)
}
