// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/model (interfaces: UsersRepository)
//
// Generated by this command:
//
//	mockgen -destination ../service/auth/mocks/users_repo_gen.go . UsersRepository
//

// Package mock_model is a generated GoMock package.
package mock_model

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersRepository is a mock of UsersRepository interface.
type MockUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsersRepositoryMockRecorder
	isgomock struct{}
}

// MockUsersRepositoryMockRecorder is the mock recorder for MockUsersRepository.
type MockUsersRepositoryMockRecorder struct {
	mock *MockUsersRepository
}

// NewMockUsersRepository creates a new mock instance.
func NewMockUsersRepository(ctrl *gomock.Controller) *MockUsersRepository {
	mock := &MockUsersRepository{ctrl: ctrl}
	mock.recorder = &MockUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersRepository) EXPECT() *MockUsersRepositoryMockRecorder {
	return m.recorder
}

// CreateWithDEK mocks base method.
func (m *MockUsersRepository) CreateWithDEK(ctx context.Context, u *model.User, dek *model.EncryptedDEK) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithDEK", ctx, u, dek)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithDEK indicates an expected call of CreateWithDEK.
func (mr *MockUsersRepositoryMockRecorder) CreateWithDEK(ctx, u, dek any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithDEK", reflect.TypeOf((*MockUsersRepository)(nil).CreateWithDEK), ctx, u, dek)
}

// GetByID mocks base method.
func (m *MockUsersRepository) GetByID(ctx context.Context, userID int) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsersRepositoryMockRecorder) GetByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsersRepository)(nil).GetByID), ctx, userID)
}

// GetByLogin mocks base method.
func (m *MockUsersRepository) GetByLogin(ctx context.Context, login string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUsersRepositoryMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUsersRepository)(nil).GetByLogin), ctx, login)
}

// GetUserDEK mocks base method.
func (m *MockUsersRepository) GetUserDEK(ctx context.Context, userID int) (*model.EncryptedDEK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDEK", ctx, userID)
	ret0, _ := ret[0].(*model.EncryptedDEK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDEK indicates an expected call of GetUserDEK.
func (mr *MockUsersRepositoryMockRecorder) GetUserDEK(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDEK", reflect.TypeOf((*MockUsersRepository)(nil).GetUserDEK), ctx, userID)
}
