// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/service/items (interfaces: FileEncryptor)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/file_encryptor_gen.go -package mocks . FileEncryptor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFileEncryptor is a mock of FileEncryptor interface.
type MockFileEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockFileEncryptorMockRecorder
	isgomock struct{}
}

// MockFileEncryptorMockRecorder is the mock recorder for MockFileEncryptor.
type MockFileEncryptorMockRecorder struct {
	mock *MockFileEncryptor
}

// NewMockFileEncryptor creates a new mock instance.
func NewMockFileEncryptor(ctrl *gomock.Controller) *MockFileEncryptor {
	mock := &MockFileEncryptor{ctrl: ctrl}
	mock.recorder = &MockFileEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileEncryptor) EXPECT() *MockFileEncryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockFileEncryptor) Decrypt(dek, nonce, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", dek, nonce, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockFileEncryptorMockRecorder) Decrypt(dek, nonce, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockFileEncryptor)(nil).Decrypt), dek, nonce, data)
}

// DecryptDEK mocks base method.
func (m *MockFileEncryptor) DecryptDEK(edek *model.EncryptedDEK) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptDEK", edek)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptDEK indicates an expected call of DecryptDEK.
func (mr *MockFileEncryptorMockRecorder) DecryptDEK(edek any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptDEK", reflect.TypeOf((*MockFileEncryptor)(nil).DecryptDEK), edek)
}

// Encrypt mocks base method.
func (m *MockFileEncryptor) Encrypt(dek, data []byte) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", dek, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockFileEncryptorMockRecorder) Encrypt(dek, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockFileEncryptor)(nil).Encrypt), dek, data)
}

// EncryptFileStream mocks base method.
func (m *MockFileEncryptor) EncryptFileStream(dek []byte, r io.Reader, w io.Writer, chunkSize int, noncePrefix, aadPrefix []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptFileStream", dek, r, w, chunkSize, noncePrefix, aadPrefix)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptFileStream indicates an expected call of EncryptFileStream.
func (mr *MockFileEncryptorMockRecorder) EncryptFileStream(dek, r, w, chunkSize, noncePrefix, aadPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptFileStream", reflect.TypeOf((*MockFileEncryptor)(nil).EncryptFileStream), dek, r, w, chunkSize, noncePrefix, aadPrefix)
}

// NewFileNoncePrefix mocks base method.
func (m *MockFileEncryptor) NewFileNoncePrefix() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFileNoncePrefix")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFileNoncePrefix indicates an expected call of NewFileNoncePrefix.
func (mr *MockFileEncryptorMockRecorder) NewFileNoncePrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFileNoncePrefix", reflect.TypeOf((*MockFileEncryptor)(nil).NewFileNoncePrefix))
}
