// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/service/items (interfaces: FileDecryptor)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/file_decryptor_gen.go -package mocks . FileDecryptor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFileDecryptor is a mock of FileDecryptor interface.
type MockFileDecryptor struct {
	ctrl     *gomock.Controller
	recorder *MockFileDecryptorMockRecorder
	isgomock struct{}
}

// MockFileDecryptorMockRecorder is the mock recorder for MockFileDecryptor.
type MockFileDecryptorMockRecorder struct {
	mock *MockFileDecryptor
}

// NewMockFileDecryptor creates a new mock instance.
func NewMockFileDecryptor(ctrl *gomock.Controller) *MockFileDecryptor {
	mock := &MockFileDecryptor{ctrl: ctrl}
	mock.recorder = &MockFileDecryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDecryptor) EXPECT() *MockFileDecryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockFileDecryptor) Decrypt(dek, nonce, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", dek, nonce, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockFileDecryptorMockRecorder) Decrypt(dek, nonce, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockFileDecryptor)(nil).Decrypt), dek, nonce, data)
}

// DecryptDEK mocks base method.
func (m *MockFileDecryptor) DecryptDEK(edek *model.EncryptedDEK) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptDEK", edek)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptDEK indicates an expected call of DecryptDEK.
func (mr *MockFileDecryptorMockRecorder) DecryptDEK(edek any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptDEK", reflect.TypeOf((*MockFileDecryptor)(nil).DecryptDEK), edek)
}

// DecryptFileStream mocks base method.
func (m *MockFileDecryptor) DecryptFileStream(dek []byte, r io.Reader, w io.Writer, chunkSize int, noncePrefix, aadPrefix []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptFileStream", dek, r, w, chunkSize, noncePrefix, aadPrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecryptFileStream indicates an expected call of DecryptFileStream.
func (mr *MockFileDecryptorMockRecorder) DecryptFileStream(dek, r, w, chunkSize, noncePrefix, aadPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptFileStream", reflect.TypeOf((*MockFileDecryptor)(nil).DecryptFileStream), dek, r, w, chunkSize, noncePrefix, aadPrefix)
}

// Encrypt mocks base method.
func (m *MockFileDecryptor) Encrypt(dek, data []byte) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", dek, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockFileDecryptorMockRecorder) Encrypt(dek, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockFileDecryptor)(nil).Encrypt), dek, data)
}
