// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/model (interfaces: ItemsRepository)
//
// Generated by this command:
//
//	mockgen -destination ../service/items/mocks/items_repo_gen.go -package mocks . ItemsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/fragpit/gophkeeper/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockItemsRepository is a mock of ItemsRepository interface.
type MockItemsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockItemsRepositoryMockRecorder
	isgomock struct{}
}

// MockItemsRepositoryMockRecorder is the mock recorder for MockItemsRepository.
type MockItemsRepositoryMockRecorder struct {
	mock *MockItemsRepository
}

// NewMockItemsRepository creates a new mock instance.
func NewMockItemsRepository(ctrl *gomock.Controller) *MockItemsRepository {
	mock := &MockItemsRepository{ctrl: ctrl}
	mock.recorder = &MockItemsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemsRepository) EXPECT() *MockItemsRepositoryMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockItemsRepository) CreateItem(ctx context.Context, userID int, item *model.ItemEncrypted) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, userID, item)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockItemsRepositoryMockRecorder) CreateItem(ctx, userID, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockItemsRepository)(nil).CreateItem), ctx, userID, item)
}

// DeleteItem mocks base method.
func (m *MockItemsRepository) DeleteItem(ctx context.Context, userID int, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockItemsRepositoryMockRecorder) DeleteItem(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockItemsRepository)(nil).DeleteItem), ctx, userID, title)
}

// GetItemByTitle mocks base method.
func (m *MockItemsRepository) GetItemByTitle(ctx context.Context, userID int, title string) (*model.ItemEncrypted, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByTitle", ctx, userID, title)
	ret0, _ := ret[0].(*model.ItemEncrypted)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByTitle indicates an expected call of GetItemByTitle.
func (mr *MockItemsRepositoryMockRecorder) GetItemByTitle(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByTitle", reflect.TypeOf((*MockItemsRepository)(nil).GetItemByTitle), ctx, userID, title)
}

// List mocks base method.
func (m *MockItemsRepository) List(ctx context.Context, userID int, iType model.ItemType) ([]model.ItemMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, iType)
	ret0, _ := ret[0].([]model.ItemMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockItemsRepositoryMockRecorder) List(ctx, userID, iType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockItemsRepository)(nil).List), ctx, userID, iType)
}

// UpdateItem mocks base method.
func (m *MockItemsRepository) UpdateItem(ctx context.Context, userID int, title string, item *model.ItemEncrypted) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, userID, title, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockItemsRepositoryMockRecorder) UpdateItem(ctx, userID, title, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockItemsRepository)(nil).UpdateItem), ctx, userID, title, item)
}
