// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fragpit/gophkeeper/internal/service/items (interfaces: ObjectStorer)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/object_storer_gen.go -package mocks . ObjectStorer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorer is a mock of ObjectStorer interface.
type MockObjectStorer struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorerMockRecorder
	isgomock struct{}
}

// MockObjectStorerMockRecorder is the mock recorder for MockObjectStorer.
type MockObjectStorerMockRecorder struct {
	mock *MockObjectStorer
}

// NewMockObjectStorer creates a new mock instance.
func NewMockObjectStorer(ctrl *gomock.Controller) *MockObjectStorer {
	mock := &MockObjectStorer{ctrl: ctrl}
	mock.recorder = &MockObjectStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorer) EXPECT() *MockObjectStorerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockObjectStorer) Delete(ctx context.Context, bucket, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, bucket, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStorerMockRecorder) Delete(ctx, bucket, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStorer)(nil).Delete), ctx, bucket, name)
}

// Get mocks base method.
func (m *MockObjectStorer) Get(ctx context.Context, bucket, name string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, bucket, name)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectStorerMockRecorder) Get(ctx, bucket, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStorer)(nil).Get), ctx, bucket, name)
}

// Put mocks base method.
func (m *MockObjectStorer) Put(ctx context.Context, name string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockObjectStorerMockRecorder) Put(ctx, name, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockObjectStorer)(nil).Put), ctx, name, r)
}
